# Generated by Django 2.2.6 on 2019-12-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked_or_not',
            field=models.BooleanField(default=False),
        ),
    ]
